//authorInfo.js
import{ref} from 'vue'
const au=ref([])
export function authors_Info(){
    function loadAuthors(){
        const authorsData = [
  // 狗區域 (狗20-狗01)
  { id: '狗20', name: 'lulu', categories: [1] },
   { id: '狗20', name: 'lulu', categories: [2] },
    { id: '狗20', name: 'lulu', categories: [3] },
  { id: '狗19', name: '小明', categories: [1] },
  { id: '狗18', name: '大名', categories: [3] },
  { id: '狗17', name: '無名', categories: [4] },
  { id: '狗16', name: '阿專', categories: [2] },
  { id: '狗15', name: '小華', categories: [1] },
  { id: '狗14', name: '老王', categories: [2] },
  { id: '狗13', name: '小李', categories: [3] },
  { id: '狗12', name: '阿美', categories: [1] },
  { id: '狗11', name: '小強', categories: [4] },
  { id: '狗10', name: '阿花', categories: [2] },
  { id: '狗09', name: '小明', categories: [1] },
  { id: '狗08', name: '大名', categories: [3] },
  { id: '狗07', name: '無名', categories: [4] },
  { id: '狗06', name: '阿專', categories: [2] },
  { id: '狗05', name: '小華', categories: [1] },
  { id: '狗04', name: '老王', categories: [2] },
  { id: '狗03', name: '小李', categories: [3] },
  { id: '狗02', name: '阿美', categories: [1] },
  { id: '狗01', name: '小強', categories: [4] },
  
  // 雞區域 (雞32-雞01)
  { id: '雞32', name: '阿花', categories: [2] },
  { id: '雞31', name: '小明', categories: [1] },
  { id: '雞30', name: '大名', categories: [3] },
  { id: '雞29', name: '無名', categories: [4] },
  { id: '雞28', name: '阿專', categories: [2] },
  { id: '雞27', name: '小華', categories: [1] },
  { id: '雞26', name: '老王', categories: [2] },
  { id: '雞25', name: '小李', categories: [3] },
  { id: '雞24', name: '阿美', categories: [1] },
  { id: '雞23', name: '小強', categories: [4] },
  { id: '雞22', name: '阿花', categories: [2] },
  { id: '雞21', name: '小明', categories: [1] },
  { id: '雞20', name: '大名', categories: [3] },
  { id: '雞19', name: '無名', categories: [4] },
  { id: '雞18', name: '阿專', categories: [2] },
  { id: '雞17', name: '小華', categories: [1] },
  { id: '雞16', name: '老王', categories: [2] },
  { id: '雞15', name: '小李', categories: [3] },
  { id: '雞14', name: '阿美', categories: [1] },
  { id: '雞13', name: '小強', categories: [4] },
  { id: '雞12', name: '阿花', categories: [2] },
  { id: '雞11', name: '小明', categories: [1] },
  { id: '雞10', name: '大名', categories: [3] },
  { id: '雞09', name: '無名', categories: [4] },
  { id: '雞08', name: '阿專', categories: [2] },
  { id: '雞07', name: '小華', categories: [1] },
  { id: '雞06', name: '老王', categories: [2] },
  { id: '雞05', name: '小李', categories: [3] },
  { id: '雞04', name: '阿美', categories: [1] },
  { id: '雞03', name: '小強', categories: [4] },
  { id: '雞02', name: '阿花', categories: [2] },
  { id: '雞01', name: '小明', categories: [1] },
  
  // 猴區域 (猴34-猴01)
  { id: '猴34', name: '大名', categories: [3] },
  { id: '猴33', name: '無名', categories: [4] },
  { id: '猴32', name: '阿專', categories: [2] },
  { id: '猴31', name: '小華', categories: [1] },
  { id: '猴30', name: '老王', categories: [2] },
  { id: '猴29', name: '小李', categories: [3] },
  { id: '猴28', name: '阿美', categories: [1] },
  { id: '猴27', name: '小強', categories: [4] },
  { id: '猴26', name: '阿花', categories: [2] },
  { id: '猴25', name: '小明', categories: [1] },
  { id: '猴24', name: '大名', categories: [3] },
  { id: '猴23', name: '無名', categories: [4] },
  { id: '猴22', name: '阿專', categories: [2] },
  { id: '猴21', name: '小華', categories: [1] },
  { id: '猴20', name: '老王', categories: [2] },
  { id: '猴19', name: '小李', categories: [3] },
  { id: '猴18', name: '阿美', categories: [1] },
  { id: '猴17', name: '小強', categories: [4] },
  { id: '猴16', name: '阿花', categories: [2] },
  { id: '猴15', name: '小明', categories: [1] },
  { id: '猴14', name: '大名', categories: [3] },
  { id: '猴13', name: '無名', categories: [4] },
  { id: '猴12', name: '阿專', categories: [2] },
  { id: '猴11', name: '小華', categories: [1] },
  { id: '猴10', name: '老王', categories: [2] },
  { id: '猴09', name: '小李', categories: [3] },
  { id: '猴08', name: '阿美', categories: [1] },
  { id: '猴07', name: '小強', categories: [4] },
  { id: '猴06', name: '阿花', categories: [2] },
  { id: '猴05', name: '小明', categories: [1] },
  { id: '猴04', name: '大名', categories: [3] },
  { id: '猴03', name: '無名', categories: [4] },
  { id: '猴02', name: '阿專', categories: [2] },
  { id: '猴01', name: '小華', categories: [1] },
  
  // 特區域 (特04-特01)
  { id: '特04', name: '老王', categories: [2] },
  { id: '特03', name: '小李', categories: [3] },
  { id: '特02', name: '阿美', categories: [1] },
  { id: '特01', name: '小強', categories: [4] },
  
  // 商區域 (商02-商01)
  { id: '商02', name: '阿花', categories: [2] },
  { id: '商01', name: '小明', categories: [1] },
  
  // 羊區域 (羊72-羊01)
  { id: '羊72', name: '大名', categories: [3] },
  { id: '羊71', name: '無名', categories: [4] },
  { id: '羊70', name: '阿專', categories: [2] },
  { id: '羊69', name: '小華', categories: [1] },
  { id: '羊68', name: '老王', categories: [2] },
  { id: '羊67', name: '小李', categories: [3] },
  { id: '羊66', name: '阿美', categories: [1] },
  { id: '羊65', name: '小強', categories: [4] },
  { id: '羊64', name: '阿花', categories: [2] },
  { id: '羊63', name: '小明', categories: [1] },
  { id: '羊62', name: '大名', categories: [3] },
  { id: '羊61', name: '無名', categories: [4] },
  { id: '羊60', name: '阿專', categories: [2] },
  { id: '羊59', name: '小華', categories: [1] },
  { id: '羊58', name: '老王', categories: [2] },
  { id: '羊57', name: '小李', categories: [3] },
  { id: '羊56', name: '阿美', categories: [1] },
  { id: '羊55', name: '小強', categories: [4] },
  { id: '羊54', name: '阿花', categories: [2] },
  { id: '羊53', name: '小明', categories: [1] },
  { id: '羊52', name: '大名', categories: [3] },
  { id: '羊51', name: '無名', categories: [4] },
  { id: '羊50', name: '阿專', categories: [2] },
  { id: '羊49', name: '小華', categories: [1] },
  { id: '羊48', name: '老王', categories: [2] },
  { id: '羊47', name: '小李', categories: [3] },
  { id: '羊46', name: '阿美', categories: [1] },
  { id: '羊45', name: '小強', categories: [4] },
  { id: '羊44', name: '阿花', categories: [2] },
  { id: '羊43', name: '小明', categories: [1] },
  { id: '羊42', name: '大名', categories: [3] },
  { id: '羊41', name: '無名', categories: [4] },
  { id: '羊40', name: '阿專', categories: [2] },
  { id: '羊39', name: '小華', categories: [1] },
  { id: '羊38', name: '老王', categories: [2] },
  { id: '羊37', name: '小李', categories: [3] },
  { id: '羊36', name: '阿美', categories: [1] },
  { id: '羊35', name: '小強', categories: [4] },
  { id: '羊34', name: '阿花', categories: [2] },
  { id: '羊33', name: '小明', categories: [1] },
  { id: '羊32', name: '大名', categories: [3] },
  { id: '羊31', name: '無名', categories: [4] },
  { id: '羊30', name: '阿專', categories: [2] },
  { id: '羊29', name: '小華', categories: [1] },
  { id: '羊28', name: '老王', categories: [2] },
  { id: '羊27', name: '小李', categories: [3] },
  { id: '羊26', name: '阿美', categories: [1] },
  { id: '羊25', name: '小強', categories: [4] },
  { id: '羊24', name: '阿花', categories: [2] },
  { id: '羊23', name: '小明', categories: [1] },
  { id: '羊22', name: '大名', categories: [3] },
  { id: '羊21', name: '無名', categories: [4] },
  { id: '羊20', name: '阿專', categories: [2] },
  { id: '羊19', name: '小華', categories: [1] },
  { id: '羊18', name: '老王', categories: [2] },
  { id: '羊17', name: '小李', categories: [3] },
  { id: '羊16', name: '阿美', categories: [1] },
  { id: '羊15', name: '小強', categories: [4] },
  { id: '羊14', name: '阿花', categories: [2] },
  { id: '羊13', name: '小明', categories: [1] },
  { id: '羊12', name: '大名', categories: [3] },
  { id: '羊11', name: '無名', categories: [4] },
  { id: '羊10', name: '阿專', categories: [2] },
  { id: '羊09', name: '小華', categories: [1] },
  { id: '羊08', name: '老王', categories: [2] },
  { id: '羊07', name: '小李', categories: [3] },
  { id: '羊06', name: '阿美', categories: [1] },
  { id: '羊05', name: '小強', categories: [4] },
  { id: '羊04', name: '阿花', categories: [2] },
  { id: '羊03', name: '小明', categories: [1] },
  { id: '羊02', name: '大名', categories: [3] },
  { id: '羊01', name: '無名', categories: [4] },
  
  // Q區域 (Q01-Q72)
  { id: 'Q01', name: '阿專', categories: [2] },
  { id: 'Q02', name: '小華', categories: [1] },
  { id: 'Q03', name: '老王', categories: [2] },
  { id: 'Q04', name: '小李', categories: [3] },
  { id: 'Q05', name: '阿美', categories: [1] },
  { id: 'Q06', name: '小強', categories: [4] },
  { id: 'Q07', name: '阿花', categories: [2] },
  { id: 'Q08', name: '小明', categories: [1] },
  { id: 'Q09', name: '大名', categories: [3] },
  { id: 'Q10', name: '無名', categories: [4] },
  { id: 'Q11', name: '阿專', categories: [2] },
  { id: 'Q12', name: '小華', categories: [1] },
  { id: 'Q13', name: '老王', categories: [2] },
  { id: 'Q14', name: '小李', categories: [3] },
  { id: 'Q15', name: '阿美', categories: [1] },
  { id: 'Q16', name: '小強', categories: [4] },
  { id: 'Q17', name: '阿花', categories: [2] },
  { id: 'Q18', name: '小明', categories: [1] },
  { id: 'Q19', name: '大名', categories: [3] },
  { id: 'Q20', name: '無名', categories: [4] },
  { id: 'Q21', name: '阿專', categories: [2] },
  { id: 'Q22', name: '小華', categories: [1] },
  { id: 'Q23', name: '老王', categories: [2] },
  { id: 'Q24', name: '小李', categories: [3] },
  { id: 'Q25', name: '阿美', categories: [1] },
  { id: 'Q26', name: '小強', categories: [4] },
  { id: 'Q27', name: '阿花', categories: [2] },
  { id: 'Q28', name: '小明', categories: [1] },
  { id: 'Q29', name: '大名', categories: [3] },
  { id: 'Q30', name: '無名', categories: [4] },
  { id: 'Q31', name: '阿專', categories: [2] },
  { id: 'Q32', name: '小華', categories: [1] },
  { id: 'Q33', name: '老王', categories: [2] },
  { id: 'Q34', name: '小李', categories: [3] },
  { id: 'Q35', name: '阿美', categories: [1] },
  { id: 'Q36', name: '小強', categories: [4] },
  { id: 'Q37', name: '阿花', categories: [2] },
  { id: 'Q38', name: '小明', categories: [1] },
  { id: 'Q39', name: '大名', categories: [3] },
  { id: 'Q40', name: '無名', categories: [4] },
  { id: 'Q41', name: '阿專', categories: [2] },
  { id: 'Q42', name: '小華', categories: [1] },
  { id: 'Q43', name: '老王', categories: [2] },
  { id: 'Q44', name: '小李', categories: [3] },
  { id: 'Q45', name: '阿美', categories: [1] },
  { id: 'Q46', name: '小強', categories: [4] },
  { id: 'Q47', name: '阿花', categories: [2] },
  { id: 'Q48', name: '小明', categories: [1] },
  { id: 'Q49', name: '大名', categories: [3] },
  { id: 'Q50', name: '無名', categories: [4] },
  { id: 'Q51', name: '阿專', categories: [2] },
  { id: 'Q52', name: '小華', categories: [1] },
  { id: 'Q53', name: '老王', categories: [2] },
  { id: 'Q54', name: '小李', categories: [3] },
  { id: 'Q55', name: '阿美', categories: [1] },
  { id: 'Q56', name: '小強', categories: [4] },
  { id: 'Q57', name: '阿花', categories: [2] },
  { id: 'Q58', name: '小明', categories: [1] },
  { id: 'Q59', name: '大名', categories: [3] },
  { id: 'Q60', name: '無名', categories: [4] },
  { id: 'Q61', name: '阿專', categories: [2] },
  { id: 'Q62', name: '小華', categories: [1] },
  { id: 'Q63', name: '老王', categories: [2] },
  { id: 'Q64', name: '小李', categories: [3] },
  { id: 'Q65', name: '阿美', categories: [1] },
  { id: 'Q66', name: '小強', categories: [4] },
  { id: 'Q67', name: '阿花', categories: [2] },
  { id: 'Q68', name: '小明', categories: [1] },
  { id: 'Q69', name: '大名', categories: [3] },
  { id: 'Q70', name: '無名', categories: [4] },
  { id: 'Q71', name: '阿專', categories: [2] },
  { id: 'Q72', name: '小華', categories: [1] }
]
        
        au.value = authorsData
        return authorsData
    }
    
    return {
        au,
        loadAuthors
    }
}